kind: pipeline
name: default

steps:
- name: argus
  image: rust:1.56.1
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustc --version
  - rustup component add rustfmt clippy
  - cargo fmt -- --check
  - cargo clippy --workspace
  - cargo test --workspace
