kind: pipeline
name: default

steps:
- name: argus
  image: rust:1.44.1
  commands:
  - rustc --version
  - rustup component add rustfmt clippy
  - cargo fmt -- --check
  - cargo clippy --workspace
  - cargo test --workspace
